MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

accounts/urls.py
from django.urls import path
from .views import HomePageView, RegistrationPageView, CustomLoginView
from django.contrib.auth.views import LogoutView


app_name = 'accounts'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('register/', RegistrationPageView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'email']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email']

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from .forms import CustomUserCreationForm
from .models import CustomUser


class HomePageView(ListView):
    model = CustomUser
    context_object_name = 'users'
    template_name = 'index.html'


class RegistrationPageView(CreateView):
    model = CustomUser
    template_name = 'registration.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('accounts:home')


class CustomLoginView(LoginView):
    template_name = 'login.html'

templates/add_post.html
{% extends 'base.html' %}

{% block main %}
    <form action="" method="POST"> {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block link %}{% endblock %}
</head>
<body>

<header>
    <nav class="navbar">
        <h1 class="brand"><a href="{% url 'accounts:home' %}" class="nav-link">HELLO</a></h1>
        <ul class="menus">
            {% if user.is_authenticated %}
                <li><a href="{% url '#' %}" class="nav-link">Add Post</a></li>
                <li><a href="{% url 'accounts:logout' %}" class="nav-link">Log out</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}" class="nav-link">Log in</a></li>
                <li><a href="{% url 'accounts:register' %}" class="nav-link">Register</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

{% block main %}{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block link %}
    <link rel="stylesheet" href="{% static 'styles/basic_styles.css' %}">
{% endblock link %}

{% block main %}

    <main class="main">
        {% for post in posts %}
            <div class="post">
    		    <img src="{{ post.image.url }}" alt="post image" class="post-img">
                <h1>{{ post.title }}</h1>
                <p>{{ post.body }}
                <a href="#" class="read-more">Read more</a></p>
            </div>
        {% endfor %}
    </main>

{% endblock main %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Log in{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'styles/basic_styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/login_registration.css' %}">
{% endblock %}

{% block main %}
    <main class="main">
        <div class="log-reg-form-container">
            <h1>Login</h1>
            <form action="" method="POST">{% csrf_token %}
                <input type="text" name="username" placeholder="Username" class="inp" required>
                <p></p>
                <input type="password" name="password" placeholder="Password" class="inp" required>
                <p></p>
                <input type="submit" value="Login" class="inp sub-btn">
            </form>
{#            <form action="" method="post">#}
{#                {{ form.as_p }}#}
{#            </form>#}
        </div>
    </main>
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts{% endblock %}

{% block link %}
	<link rel="stylesheet" href="{% static 'styles/basic_styles.css' %}">
{% endblock %}

{% block main %}
    <main class="main">
        <div class="post">
            <img src="https://i.pinimg.com/originals/f5/25/6f/f5256f22b9dea5d4eb80c41f91f87793.jpg" alt="post image" class="post-img">
            <h1>Title</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias atque earum eum exercitationem ratione tenetur. Enim eveniet in inventore ipsum perspiciatis! A ab at illo pariatur placeat sapiente sint, totam?</p>
        </div>
        <div class="back">
            <a href="#" class="go-back-link">
                <span class="go-back-text">Go to back</span>
            </a>
        </div>
    </main>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'styles/basic_styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/login_registration.css' %}">
{% endblock %}

{% block main %}
    <main class="main">
        <div class="log-reg-form-container">
            <h1>Register</h1>
            <form action="" method="POST"> {% csrf_token %}
                <input type="text" name="first_name" placeholder="First name" class="inp" required>
                <p></p>
                <input type="text" name="last_name" placeholder="Last name" class="inp" required>
                <p></p>
                <input type="text" name="username" placeholder="Username" class="inp" required>
                <p></p>
                <input type="email" name="email" placeholder="Email" class="inp" required>
                <p></p>
                <input type="password" name="password1" placeholder="Password" class="inp" required>
                <p></p>
                <input type="password" name="password2" placeholder="Password" class="inp" required>
                <p></p>
                <input type="submit" value="Register" class="inp sub-btn">
            </form>

{#            <form action="">#}
{#                {{ form.as_p }}#}
{#            </form>#}
        </div>
    </main>
{% endblock %}